//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024/11/27 10:27:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using IntelligentMonitoringSystem.Domain.PersonnelAccessRecords;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IntelligentMonitoringSystem.Infrastructure.EntityFrameworkCore.EntityTypeConfigurations;

/// <summary>
///     There are no comments for PersonnelAccessRecordConfiguration in the schema.
/// </summary>
public class PersonnelAccessRecordConfiguration : IEntityTypeConfiguration<PersonnelAccessRecord>
{
    /// <summary>
    ///     Configures the entity type for the PersonnelAccessRecord entity.
    /// </summary>
    /// <param name="builder">builder</param>
    public void Configure(EntityTypeBuilder<PersonnelAccessRecord> builder)
    {
        builder.ToTable(@"personnel_access_record");
        builder.Property(x => x.Id).HasColumnName(@"id").HasColumnType(@"int").IsRequired();
        builder.Property(x => x.FaceId).HasColumnName(@"face_id").HasColumnType(@"varchar(64)").IsRequired();
        builder.Property(x => x.DeviceId).HasColumnName(@"device_id").HasColumnType(@"varchar(20)").IsRequired();
        builder.Property(x => x.DeviceName).HasColumnName(@"device_name").HasColumnType(@"nvarchar(30)")
            .IsRequired();
        builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar(64)").IsRequired();
        builder.Property(x => x.Age).HasColumnName(@"age").IsRequired();
        builder.Property(x => x.Gender).HasColumnName(@"gender").HasColumnType(@"char(1)").IsRequired();
        builder.Property(x => x.AccessType).HasColumnName(@"access_type").HasColumnType(@"char(1)").IsRequired();
        builder.Property(x => x.AccessStatus).HasColumnName(@"access_status").HasColumnType(@"char(1)")
            .IsRequired();
        builder.Property(x => x.AccessTime).HasColumnName(@"access_time").IsRequired();
        builder.Property(x => x.OriginalFaceUrl).HasColumnName(@"original_face_url").HasColumnType(@"varchar(300)")
            .IsRequired();
        builder.Property(x => x.OriginalSnapUrl).HasColumnName(@"original_snap_url").HasColumnType(@"varchar(300)")
            .IsRequired();
        builder.Property(x => x.RecognitionFaceOssUrl).HasColumnName(@"recognition_face_oss_url")
            .HasColumnType(@"varchar(300)")
            .IsRequired();
        builder.Property(x => x.SnapImgPath).HasColumnName(@"snap_img_path").HasColumnType(@"varchar(300)");
        builder.Property(x => x.FaceImgPath).HasColumnName(@"face_img_path").HasColumnType(@"varchar(300)");
        builder.Property(x => x.RecognitionFacePath).HasColumnName(@"recognition_face_path")
            .HasColumnType(@"nvarchar(300)");
        builder.Property(x => x.LeaveStatus).HasColumnName(@"leave_status").HasColumnType(@"char(1)").IsRequired();
        builder.Property(x => x.CreateTime).HasColumnName(@"create_time").IsRequired();
        builder.Property(x => x.LastEditTime).HasColumnName(@"last_edit_time");
        builder.Property(x => x.ExpectedReturnTime).HasColumnName("expected_return_time");
        builder.Property(x => x.LastEditUserId).HasColumnName(@"last_edit_user_id").HasColumnType(@"varchar(64)");
        builder.Property(x => x.LastEditUserName).HasColumnName(@"last_edit_user_name")
            .HasColumnType(@"varchar(64)");
        builder.Property(x => x.Remark).HasColumnName(@"remark").HasColumnType(@"varchar(100)");
        builder.Property(x => x.DevicePlayback).HasColumnName(@"device_playback").HasColumnType(@"varchar(120)");
        builder.Property(x => x.LeaveApplicationId).HasColumnName(@"leave_application_id").HasColumnType(@"int");
        builder.Property(x => x.EventIdentifier).HasColumnName(@"event_identifier").IsRequired();
        builder.HasKey(@"Id");
        builder.Ignore(x => x.TopicAlarmEventLog);
        builder.Ignore(x => x.AbnormalPersonnelAccessRecord);
        builder.Ignore(x => x.Nurse);
        builder.Ignore(x => x.RoomNo);
        builder.HasIndex(@"AccessStatus").HasDatabaseName(@"ix_personnel_access_record_access_status");
        builder.HasIndex(@"AccessTime").HasDatabaseName(@"ix_personnel_access_record_access_time");
        builder.HasIndex(@"CreateTime").HasDatabaseName(@"ix_personnel_access_record_create_time");
        builder.HasIndex(@"EventIdentifier").IsUnique()
            .HasDatabaseName(@"ix_personnel_access_record_event_identifier");
    }
}