//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024/11/27 10:27:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using IntelligentMonitoringSystem.Domain.PersonnelAccessRecords;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IntelligentMonitoringSystem.Infrastructure.EntityFrameworkCore.EntityTypeConfigurations;

/// <summary>
///     There are no comments for TopicAlarmEventLogConfiguration in the schema.
/// </summary>
public class TopicAlarmEventLogConfiguration : IEntityTypeConfiguration<TopicAlarmEventLog>
{
    /// <summary>
    ///     There are no comments for Configure(EntityTypeBuilder TopicAlarmEventLog builder) method in the schema.
    /// </summary>
    /// <param name="builder">builder</param>
    public void Configure(EntityTypeBuilder<TopicAlarmEventLog> builder)
    {
        builder.ToTable(@"topic_alarm_event_log");
        builder.Property(x => x.Id).HasColumnName(@"id").HasColumnType(@"int").IsRequired();
        builder.Property(x => x.PersonnelAccessRecordId).HasColumnName(@"personnel_access_record_id")
            .HasColumnType(@"int").IsRequired();
        builder.Property(x => x.AppId).HasColumnName(@"app_id").HasColumnType(@"varchar(50)").IsRequired();
        builder.Property(x => x.MsgType).HasColumnName(@"msg_type").HasColumnType(@"varchar(50)").IsRequired();
        builder.Property(x => x.TimeStamp).HasColumnName(@"time_stamp").IsRequired();
        builder.Property(x => x.Sig).HasColumnName(@"sig").HasColumnType(@"VARCHAR(50)").IsRequired();
        builder.Property(x => x.DeviceId).HasColumnName(@"device_id").HasColumnType(@"VARCHAR(50)").IsRequired();
        builder.Property(x => x.DeviceName).HasColumnName(@"device_name").HasColumnType(@"nvarchar(32)");
        builder.Property(x => x.DetectTime).HasColumnName(@"detect_time").IsRequired();
        builder.Property(x => x.AlarmContext).HasColumnName(@"alarm_context").HasColumnType(@"nvarchar(2048)")
            .IsRequired();
        builder.Property(x => x.DeviceAddress).HasColumnName(@"device_address").HasColumnType(@"nvarchar(64)");
        builder.Property(x => x.RegionName).HasColumnName(@"region_name").HasColumnType(@"nvarchar(64)");
        builder.Property(x => x.StoreName).HasColumnName(@"store_name").HasColumnType(@"nvarchar(64)");
        builder.Property(x => x.StoreId).HasColumnName(@"store_id").HasColumnType(@"varchar(32)");
        builder.Property(x => x.Region).HasColumnName(@"region").HasColumnType(@"varchar(32)");
        builder.HasKey(@"Id");
    }
}