apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligentmonitoringsystem-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligentmonitoringsystem-webapi
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: intelligentmonitoringsystem-webapi
    spec:
      containers:
        - name: intelligentmonitoringsystem-webapi
          image: ${ImageName}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://*:8080"
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Staging"
      