//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024/11/27 10:27:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using IntelligentMonitoringSystem.Domain.Shared.Contracts.Entities;

namespace IntelligentMonitoringSystem.Domain.PersonnelAccessRecords;

/// <summary>
///     监控采集日志
/// </summary>
public class TopicAlarmEventLog : IEntity
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="TopicAlarmEventLog" /> class.
    /// </summary>
    public TopicAlarmEventLog() { }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TopicAlarmEventLog" /> class.
    ///     创建监控采集日志
    /// </summary>
    /// <param name="appId">appId</param>
    /// <param name="msgType">msgType</param>
    /// <param name="timeStamp">timeStamp</param>
    /// <param name="sig">sig</param>
    /// <param name="deviceId">deviceId</param>
    /// <param name="detectTime">detectTime</param>
    /// <param name="alarmContext">alarmContext</param>
    /// <param name="deviceName">设备名称</param>
    /// <param name="deviceAddress">设备地址</param>
    /// <param name="regionName">区域名称</param>
    /// <param name="storeName">店铺名称</param>
    /// <param name="storeId">店铺Id</param>
    /// <param name="region">区域</param>
    public TopicAlarmEventLog(string appId, string msgType, DateTime timeStamp,
        string sig, string deviceId, DateTime detectTime, string alarmContext, string deviceName,
        string deviceAddress, string storeName, string storeId, string regionName, string region)
    {
        AppId = appId;
        MsgType = msgType;
        TimeStamp = timeStamp;
        Sig = sig;
        DeviceId = deviceId;
        DetectTime = detectTime;
        AlarmContext = alarmContext;
        DeviceName = deviceName;
        DeviceAddress = deviceAddress;
        RegionName = regionName;
        StoreName = storeName;
        StoreId = storeId;
        Region = region;
    }

    /// <summary>
    ///     Id
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    ///     关联用户访问记录Id
    /// </summary>
    public int PersonnelAccessRecordId { get; set; }

    /// <summary>
    ///     AppId
    /// </summary>
    public string AppId { get; set; }

    /// <summary>
    ///     MsgType
    /// </summary>
    public string MsgType { get; set; }

    /// <summary>
    ///     TimeStamp
    /// </summary>
    public DateTime TimeStamp { get; set; }

    /// <summary>
    ///     Sig
    /// </summary>
    public string Sig { get; set; }

    /// <summary>
    ///     设备Id
    /// </summary>
    public string DeviceId { get; set; }

    /// <summary>
    ///     采集时间
    /// </summary>
    public DateTime DetectTime { get; set; }

    /// <summary>
    ///     报警上下文
    /// </summary>
    public string AlarmContext { get; set; }

    /// <summary>
    ///     设备名称
    /// </summary>
    public string DeviceName { get; set; }

    /// <summary>
    ///     设备地址
    /// </summary>
    public string DeviceAddress { get; set; }

    /// <summary>
    ///     区域名称
    /// </summary>
    public string RegionName { get; set; }

    /// <summary>
    ///     店铺名称
    /// </summary>
    public string StoreName { get; set; }

    /// <summary>
    ///     店铺Id
    /// </summary>
    public string StoreId { get; set; }

    /// <summary>
    ///     区域
    /// </summary>
    public string Region { get; set; }
}